"""
AI Optimizer — Asynchronous Background Optimizer
─────────────────────────────────────────────
Monitors trading strategies for poor performance.
If a strategy is failing (e.g., disabled by Reset Loop),
it leverages the AIEngine to analyze and improve the code.

Modes:
- "manual": saves suggested improvements as pending, requiring user approval.
- "auto": dynamically saves and hot-reloads the improved strategy into the StrategyManager.
"""

import asyncio
import logging
from pathlib import Path
import json
import time
from api.server import broadcast

logger = logging.getLogger("xiaoxiao.ai_optimizer")

class AIOptimizer:
    def __init__(self, mode: str = "manual"):
        """
        mode: 'manual' or 'auto'.
        """
        self.mode = mode
        self.check_interval = 3600  # Check every hour
        self.is_running = False
        
        self.pending_dir = Path("backend/custom_strategies/pending_approval")
        self.pending_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"AIOptimizer initialized in {self.mode.upper()} mode")

    async def run_loop(self, state: dict):
        """Asynchronous loop to monitor strategy performance."""
        self.is_running = True
        logger.info("AI Optimizer loop started.")
        
        while self.is_running:
            try:
                await self._check_and_optimize(state)
            except asyncio.CancelledError:
                logger.info("AI Optimizer loop cancelled.")
                break
            except Exception as e:
                logger.error(f"Error in AI Optimizer loop: {e}", exc_info=True)
                
            await asyncio.sleep(self.check_interval)
            
    async def _check_and_optimize(self, state: dict):
        """Check for disabled strategies and trigger optimization."""
        if not state.get("running", False):
            return
            
        ai_engine = state.get("ai_engine")
        if not ai_engine or not ai_engine.available:
            return
            
        reset_loop_inst = state.get("reset_loop")
        strategy_manager = state.get("strategy_manager")
        strategies = state.get("strategies", [])
        
        if not reset_loop_inst or not strategy_manager:
            return
            
        for strategy in strategies:
            # We target strategies that are currently disabled by the reset loop
            if reset_loop_inst.is_strategy_disabled(strategy.name):
                logger.info(f"AI Optimizer: Strategy '{strategy.name}' is disabled. Initiating improvement protocol.")
                await broadcast({"type": "ai_update", "strategy": strategy.name, "message": f"Strategy is disabled. Initiating improvement protocol..."})
                await self._optimize_strategy(strategy, state, ai_engine, strategy_manager)

    async def _optimize_strategy(self, strategy, state: dict, ai_engine, strategy_manager):
        """Gathers data and asks the AI to improve the strategy."""
        
        # Gather backtest-like results (current performance)
        paper_trader = state.get("paper_trader")
        if not paper_trader:
            return
            
        # Get history for this strategy
        trades = [t for t in paper_trader.trade_history if t.strategy_name == strategy.name]
        wins = [t for t in trades if t.pnl_net > 0]
        losses = [t for t in trades if t.pnl_net <= 0]
        
        win_rate = len(wins) / len(trades) if trades else 0
        total_pnl = sum(t.pnl_net for t in trades)
        
        results = {
            "total_trades": len(trades),
            "win_rate": win_rate,
            "total_pnl": total_pnl,
            "avg_win": sum(t.pnl_net for t in wins) / len(wins) if wins else 0,
            "avg_loss": sum(t.pnl_net for t in losses) / len(losses) if losses else 0
        }
        
        # Get strategy code
        code = self._get_source_code(strategy.name, strategy_manager)
        if not code:
            logger.warning(f"Could not find source code for {strategy.name}. Cannot optimize.")
            return
            
        logger.info(f"Requesting AI improvement for {strategy.name}...")
        await broadcast({"type": "ai_update", "strategy": strategy.name, "message": "Analyzing trade history and generating improved code..."})
        improvement_data = await ai_engine.improve_strategy(strategy.name, code, results)
        
        if improvement_data.get("parse_error"):
            logger.error(f"Failed to parse AI response for {strategy.name}")
            return
            
        improved_code = improvement_data.get("improved_code")
        if not improved_code:
            logger.warning(f"No improved code generated by AI for {strategy.name}")
            return
            
        new_name = f"Improved_{strategy.name.replace(' ', '_')}_{int(time.time())}"
        
        if self.mode == "auto":
            logger.info(f"Auto Mode: Saving and reloading new strategy '{new_name}'")
            await broadcast({"type": "ai_update", "strategy": strategy.name, "message": f"Auto-saving and hot-reloading improved strategy as {new_name}"})
            filepath = strategy_manager.save_strategy_code(new_name, improved_code)
            new_strategy = strategy_manager.reload_strategy(new_name)
            if new_strategy:
                # Add to state strategies list
                state["strategies"].append(new_strategy)
                logger.info(f"Successfully hot-reloaded {new_name} into active strategies.")
                
                # Optional: Remove old strategy from state to fully replace it
                state["strategies"] = [s for s in state["strategies"] if s.name != strategy.name]
                logger.info(f"Deactivated old failing strategy: {strategy.name}")
                await broadcast({"type": "ai_update", "strategy": strategy.name, "message": f"Successfully activated {new_name}."})
        else:
            logger.info(f"Manual Mode: Saving suggested strategy '{new_name}' to pending folder.")
            await broadcast({"type": "ai_update", "strategy": strategy.name, "message": f"Manual mode: Improvement saved to pending folder for review."})
            safe_name = "".join(c if c.isalnum() or c == "_" else "_" for c in new_name.lower())
            filepath = self.pending_dir / f"{safe_name}.py"
            filepath.write_text(improved_code, encoding="utf-8")
            
            # Save explanation markdown
            report_path = self.pending_dir / f"{safe_name}_report.md"
            report_content = (
                f"# AI Optimization Report for {strategy.name}\n\n"
                f"**Assessment:** {improvement_data.get('assessment', 'N/A')}\n\n"
                f"**Confidence:** {improvement_data.get('confidence_in_improvement', 'N/A')}\n\n"
                f"**Improvements:**\n{json.dumps(improvement_data.get('improvements', []), indent=2)}\n\n"
                f"**Honest Note:** {improvement_data.get('honest_note', 'N/A')}\n"
            )
            report_path.write_text(report_content, encoding="utf-8")
            
    def _get_source_code(self, name: str, strategy_manager) -> str:
        """Attempt to read the source code of the strategy."""
        code = strategy_manager.get_strategy_code(name)
        if code:
            return code
            
        # Fallback for built-in strategies
        import inspect
        import sys
        
        for strategy in strategy_manager.get_all_strategies(builtin_strategies=[]):
            pass # Not perfect since we don't have builtin list directly here
            
        # Let's try to find it in the imported modules
        for mod_name, module in sys.modules.items():
            if mod_name.startswith("engine.strategies."):
                for attr_name in dir(module):
                    attr = getattr(module, attr_name)
                    if isinstance(attr, type) and hasattr(attr, "name") and getattr(attr, "name") == name:
                        try:
                            return inspect.getsource(module)
                        except Exception:
                            pass
        return ""
